name: "🚀 Deploy to PROD environment"

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [frontend, backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          echo "Building and testing ${{ matrix.package }}"
          cd ${{ matrix.package }} && npm install

  deploy-prod:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix:
        package: [frontend, backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to test environment
        run: |
          echo "Deploying to prod environment ${{ matrix.package }}"
